version: '3.8'

services:
  api-gateway:
    build: 
      context: ./src/api-gateway
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=your-secret-key-here
      - PLANNING_SERVICE_URL=http://planning-service:8080
    depends_on:
      - planning-service
    networks:
      - budget-network

  planning-service:
    build: 
      context: ./src/planning-service
      dockerfile: Dockerfile
    environment:
      - USE_IN_MEMORY=true
    networks:
      - budget-network

networks:
  budget-network:
    driver: bridge
